fieldLayouts:
  b475ad36-22ce-4170-b512-ad44147a3313:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: fe82f696-f8f1-4ec9-8cff-79efd8ad55a9
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: f7644589-3224-4d50-b0be-22ad80608b4a
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: a3be48c4-b84f-4b94-a0f4-1f0024273160
        userCondition: null
fs: images
handle: images
name: Afbeeldingen
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
